spring.datasource.url=jdbc:postgresql://ep-fancy-shadow-atxmk1ot-pooler.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&options=-c%20timezone=America/Sao_Paulo

spring.datasource.username=neondb_owner
spring.datasource.password=npg_dxm1tJQ9LBps

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
